//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backoffice.server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/MyWebshopContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<server.Order>))]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MomentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object WebshopCallbackField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Moment {
            get {
                return this.MomentField;
            }
            set {
                if ((this.MomentField.Equals(value) != true)) {
                    this.MomentField = value;
                    this.RaisePropertyChanged("Moment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object WebshopCallback {
            get {
                return this.WebshopCallbackField;
            }
            set {
                if ((object.ReferenceEquals(this.WebshopCallbackField, value) != true)) {
                    this.WebshopCallbackField = value;
                    this.RaisePropertyChanged("WebshopCallback");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="server", ConfigurationName="server.IBackoffice")]
    public interface IBackoffice {
        
        [System.ServiceModel.OperationContractAttribute(Action="server/IBackoffice/GetOrderList", ReplyAction="server/IBackoffice/GetOrderListResponse")]
        System.Collections.Generic.List<server.Order> GetOrderList();
        
        [System.ServiceModel.OperationContractAttribute(Action="server/IBackoffice/GetOrderList", ReplyAction="server/IBackoffice/GetOrderListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<server.Order>> GetOrderListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="server/IBackoffice/ShipOrder", ReplyAction="server/IBackoffice/ShipOrderResponse")]
        bool ShipOrder(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="server/IBackoffice/ShipOrder", ReplyAction="server/IBackoffice/ShipOrderResponse")]
        System.Threading.Tasks.Task<bool> ShipOrderAsync(string ProductId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackofficeChannel : server.IBackoffice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackofficeClient : System.ServiceModel.ClientBase<server.IBackoffice>, server.IBackoffice {
        
        public BackofficeClient() {
        }
        
        public BackofficeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackofficeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackofficeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackofficeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<server.Order> GetOrderList() {
            return base.Channel.GetOrderList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<server.Order>> GetOrderListAsync() {
            return base.Channel.GetOrderListAsync();
        }
        
        public bool ShipOrder(string ProductId) {
            return base.Channel.ShipOrder(ProductId);
        }
        
        public System.Threading.Tasks.Task<bool> ShipOrderAsync(string ProductId) {
            return base.Channel.ShipOrderAsync(ProductId);
        }
    }
}
